# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)
xcode_select "/Applications/Xcode.app"

platform :ios do
  desc "打包 build_app_store 版本"
  lane :build_app_store do
    # add actions here: https://docs.fastlane.tools/actions
    gym(
    	scheme:"PushupsApp",
    	export_method:"app-store",
    	output_directory:"./fastlane/build",
    	archive_path:"./Archive",
    	clean: true,
    	)

    update_app_store
  end

  desc "上传 app store"
  lane :update_app_store do
  	increment_build_number
  	# 编译代码
  	gym(
  		scheme:"PushupsApp",
  		export_method:"app-store",
  		)
  	# 发布到 Apple Store
  	deliver
  end

  desc "上传 dSYM 到crashlytics "
  lane :update_to_crashlytics do

  	upload_symbols_to_crashlytics(
  		dsym_path: "./fastlane/build/项目名.app.dSYM.zip",
  		api_token: “你自己的touken”
  		)

  end

  desc "截屏处理"
  lane :screenshots do
    capture_screenshots(stop_after_first_error: true)
  end

end
